//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public Adresse()
        {
            this.AlleBenutzer = new HashSet<Benutzer>();
        }
    
        public int ID { get; set; }
        public string Adressdaten { get; set; }
        public System.DateTime ErstelltAm { get; set; }
    
        public virtual Ort Ort { get; set; }
        public virtual ICollection<Benutzer> AlleBenutzer { get; set; }
    }
}
