//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public Benutzer()
        {
            this.AlleBuchungen = new HashSet<Buchung>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public byte[] Passwort { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public bool Geschlecht { get; set; }
        public string Telefon { get; set; }
        public string Titel { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public bool Ist_Mitarbeiter { get; set; }
        public System.DateTime ErstelltAm { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Land Land { get; set; }
        public virtual ICollection<Buchung> AlleBuchungen { get; set; }
    }
}
