//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public Benutzer()
        {
            this.AlleBuchungen = new HashSet<Buchung>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public byte[] Passwort { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public bool Geschlecht { get; set; }
        public string Telefon { get; set; }
        public string Titel { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public bool Ist_Mitarbeiter { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Land Land { get; set; }
        public virtual ICollection<Buchung> AlleBuchungen { get; set; }
    }
}
