//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bewertung
    {
        public int ID { get; set; }
        public int Wertung { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
    
        public virtual Reise Reise { get; set; }
    }
}
