//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public int ID { get; set; }
        public string Passnummer { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public System.DateTime ErstelltAm { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Reisedatum Reisedatum { get; set; }
        public virtual Buchung_Zahlung Buchung_Zahlung { get; set; }
        public virtual BuchungStorniert BuchungStorniert { get; set; }
    }
}
