//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public int Reisedurchfuehrung_ID { get; set; }
        public string Passnummer { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Reisedurchfuehrung Reisedurchfuehrung { get; set; }
        public virtual Buchung_Zahlung Buchung_Zahlung { get; set; }
        public virtual BuchungStorniert BuchungStorniert { get; set; }
    }
}
