//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reisebueroEntities : DbContext
    {
        public reisebueroEntities()
            : base("name=reisebueroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresse> AlleAdressen { get; set; }
        public DbSet<Benutzer> AlleBenutzer { get; set; }
        public DbSet<Bewertung> AlleBewertungen { get; set; }
        public DbSet<Bild> AlleBilder { get; set; }
        public DbSet<Buchung> AlleBuchungen { get; set; }
        public DbSet<Buchung_Zahlung> AlleBuchung_Zahlungen { get; set; }
        public DbSet<BuchungStorniert> AlleBuchungenStorniert { get; set; }
        public DbSet<Land> AlleLaender { get; set; }
        public DbSet<Ort> AlleOrte { get; set; }
        public DbSet<Reise> AlleReisen { get; set; }
        public DbSet<Reise_Bild> AlleReise_Bilder { get; set; }
        public DbSet<Reisedatum> AlleReisedaten { get; set; }
        public DbSet<Reisedurchfuehrung> AlleReisedurchfuehrungen { get; set; }
        public DbSet<Unterkunft> AlleUnterkuenfte { get; set; }
        public DbSet<Unterkunft_Bild> AlleUnterkunft_Bilder { get; set; }
        public DbSet<Verpflegung> AlleVerpflegungen { get; set; }
        public DbSet<Zahlung> AlleZahlungen { get; set; }
        public DbSet<Zahlungsart> AlleZahlungsarten { get; set; }
    }
}
