//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ort
    {
        public Ort()
        {
            this.AlleAdressen = new HashSet<Adresse>();
            this.AlleReisen = new HashSet<Reise>();
        }
    
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
    
        public virtual ICollection<Adresse> AlleAdressen { get; set; }
        public virtual Land Land { get; set; }
        public virtual ICollection<Reise> AlleReisen { get; set; }
    }
}
