//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reisedatum
    {
        public Reisedatum()
        {
            this.AlleReisedurchfuehrungen = new HashSet<Reisedurchfuehrung>();
        }
    
        public int ID { get; set; }
        public System.DateTime Startdatum { get; set; }
        public System.DateTime Enddatum { get; set; }
        public System.DateTime Anmeldefrist { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
    
        public virtual Reise Reise { get; set; }
        public virtual ICollection<Reisedurchfuehrung> AlleReisedurchfuehrungen { get; set; }
    }
}
