//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reise
    {
        public Reise()
        {
            this.AlleBewertungen = new HashSet<Bewertung>();
            this.AlleReise_Bilder = new HashSet<Reise_Bild>();
            this.AlleReisedaten = new HashSet<Reisedatum>();
        }
    
        public int ID { get; set; }
        public string Titel { get; set; }
        public string Beschreibung { get; set; }
        public decimal Preis_Erwachsener { get; set; }
        public decimal Preis_Kind { get; set; }
        public System.DateTime ErstelltAm { get; set; }
    
        public virtual ICollection<Bewertung> AlleBewertungen { get; set; }
        public virtual Ort Ort { get; set; }
        public virtual ICollection<Reise_Bild> AlleReise_Bilder { get; set; }
        public virtual Unterkunft Unterkunft { get; set; }
        public virtual ICollection<Reisedatum> AlleReisedaten { get; set; }
    }
}
