//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unterkunft
    {
        public Unterkunft()
        {
            this.AlleReisen = new HashSet<Reise>();
            this.AlleUnterkunft_Bilder = new HashSet<Unterkunft_Bild>();
        }
    
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public int Kategorie { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
    
        public virtual ICollection<Reise> AlleReisen { get; set; }
        public virtual ICollection<Unterkunft_Bild> AlleUnterkunft_Bilder { get; set; }
        public virtual Verpflegung Verpflegung { get; set; }
    }
}
