//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_Reiseboerse_Graf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahlung
    {
        public Zahlung()
        {
            this.AlleBuchung_Zahlungen = new HashSet<Buchung_Zahlung>();
        }
    
        public int ID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Nummer { get; set; }
        public System.DateTime ErstelltAm { get; set; }
    
        public virtual ICollection<Buchung_Zahlung> AlleBuchung_Zahlungen { get; set; }
        public virtual Zahlungsart Zahlungsart { get; set; }
    }
}
